### ISSUE TITLE
 Is there a way in the graphic to see exposure over time for a subject? 

### ISSUE THREAD

**Issue by rinjaj** [SafetyGraphics/safety-eDISH#211]
In step 2E is there a way in the graphic once you click on an individual subject to see the exposure time points on the linear graphic of lab values?  In other words, is there a way in the graphic to see exposure over time for a subject?

**Comment by jwildfire** [comment]
This is a very common request, but adding a second data domain to capture treatment exposure is complicated, so we've decided to delay the feature until after our v1.0 release. Definitely high priority though.

**Comment by samussiah** [comment]
One route is to add SDTM's exposure domain (EX) and annotate timepoints/time intervals:

![exposure](https://user-images.githubusercontent.com/5428548/57247208-39e97e00-700d-11e9-8f0a-0e31fd9cd566.png)

This participant received Xanomeline from study day 1-15, 16-168, and 169-181.  This method wouldn't work so well with overlapping treatments though, in which case we could try something out like this:

![image](https://user-images.githubusercontent.com/5428548/57247550-28ed3c80-700e-11e9-853e-51a1db0b8f34.png)
