### ISSUE TITLE
Can we describe what is temple corollary? 

### ISSUE THREAD

**Issue by rinjaj** [SafetyGraphics/safety-eDISH#213]
What is temple’s corollary?  (This is included in the user manual but perhaps this points to the option of having some definitions/footnotes etc. describing items on the actual graphical display page)

Solution: Add footnote?

**Comment by jwildfire** [comment]
Happy to add a footnote if someone can provide the appropriate text ...

**Comment by jwildfire** [comment]
Duplicates #107
