### ISSUE TITLE
Display raw value, instead of just parameter for graphics?

### ISSUE THREAD

**Issue by rinjaj** [SafetyGraphics/safety-eDISH#214]
•In raw lab value summary table, it would be great to list individual raw values instead of just parameters. 
o	Same thing goes for the time course graph. It would be better if it is interactive and there is an option to display raw value for Y axis.

**Comment by jwildfire** [comment]
For the first bullet, users can click to expand the chart, and then mouseover each point to see the exact value.

For the second bullet, it's hard to use raw units in that chart, since the scales for each measure can be quite different (depending on the units).
